export type BlockType =
  | "hero"
  | "elevating_essentials"
  | "game_changer"
  | "features"
  | "store_brands"
  | "sustainability"
  | "product_carousel"
  | "testimonials"
  | "newsletter"
  | "about_hero_section"
  | "about_story"
  | "about_mission"
  | "about_sustainability"
  | "about_team"
  | "about_customer_impact"

export type ContentBlockType =
  | "heading"
  | "text"
  | "image"
  | "video"
  | "button"
  | "hero"
  | "features"
  | "testimonials"
  | "newsletter"
  | "product_gallery"
  | "blog_preview"
  | "store_brands"
  | "sustainability"
  | "product_carousel"
  | "elevating_essentials"
  | "game_changer"
  | "competitor_comparison"
  | "about_hero_section"
  | "about_story"
  | "about_sustainability"
  | "about_team"
  | "about_customer_impact"
  | "contact_hero"
  | "contact_details"
  | "contact_form"
  | "contact_faq"
  | "contact_business"

export type PageViewType = "page_view" | "exit"

export type PromoCodeType = "percentage" | "fixed_amount"

export type SupportedLanguage = "en" | "fr" | "uk"